on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # runs at 12:00 UTC every Wed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          script: |
            const script = require('./.github/workflows/script.js')
            await script({github, context})