on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3" # runs at 0:00 UTC every Wed

env:
  REF_VER: 3.1.1
  REF_DATE: 2022-09-28
  PERIOD: 18

jobs:
  scheduler:
    if: github.repository_owner == 'King-of-Infinite-Space'
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.step1.outputs.continue }}
    steps:
      - id: step1
        run: |
          days=$(( ($(date +%s)-$(date +%s --date $REF_DATE))/(3600*24) ))
          echo "$days days since reference v$REF_VER"
          continue=$(( days % $PERIOD < 7 ))
          [[ "$GITHUB_EVENT_NAME" = 'workflow_dispatch' ]] && continue=1
          echo "continue=$continue" >> $GITHUB_OUTPUT

  updater:
    needs: scheduler
    if: needs.scheduler.outputs.continue == 1
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: execute python script
        env:
          MSG_URL: ${{ secrets.MSG_URL }}
          PAYLOAD1: ${{ secrets.PAYLOAD1 }}
          NOTION_GENSHIN: ${{ secrets.NOTION_GENSHIN }}
        run: python ./utils/fetch_data.py
