on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: install python packages
        run: |
          pip install -r requirements.txt

      - name: execute python script
        env:
          MSG_URL: ${{ secrets.MSG_URL }}
          PAYLOAD1: ${{ secrets.PAYLOAD1 }}
          NOTION_GENSHIN: ${{ secrets.NOTION_GENSHIN }}
        run: python ./utils/fetch_data.py
