on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
          
      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute python script
        id: script
        run: python fetch_data.py

      - name: get message
        id: message
        run: echo "::set-output name=msg::$(cat msg.log)"

      - name: commit changes
        if: ${{ steps.message.outputs.msg != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.message.outputs.msg }}
      
      - name: send message
        if: ${{ steps.message.outputs.msg != '' }}
        env:
          MSG_URL: ${{ secrets.MSG_URL }}
          PAYLOAD1: ${{ secrets.PAYLOAD1 }}
          MSG: ${{ steps.message.outputs.msg }}
        run:
          curl -G \
            --data-urlencode $PAYLOAD1 \
            --data-urlencode "text=$MSG" \
            $MSG_URL > /dev/null

      - name: raise error if incomplete
        if: ${{ contains(steps.message.outputs.msg,'incomplete') }}
        run: exit 1